// Reference are stored in the Heap
// Primitive values are stored in stack

//this in function and this ()=> Lexical 
//what is this
//promises are handled by .then and await can also be used by promises so can every .then code be converted with await

// private variable should start with _ (_data)

// constructor function ki jaga ab class keyword use hota hy? JS ma (baki languages)
//Es5 is confusing
//puri video dekho ES5 ma phir wo aagye chal kar ES6 ma bhi karwa deta hy

//babel and webpack
//d/b export and export default
//common js se export ho aur module js se import ho sagta hy?
//js ki classes aur regx syntax same hy like other languages??
// react ma .map kyu use karty hyn forEach kyu nhi
// OOP code ki example chiye mujhe 