// Reference are stored in the Heap
// Primitive values are stored in stack

//this in function and this ()=> Lexical 

//promises are handled by .then and await can also be used by promises so can every .then code be converted with await

// private variable should start with _ (_data)

// constructor function ki jaga ab class keyword use hota hy? JS ma 
//Es5 is confusing
//puri video dekho ES5 ma phir wo aagye chal kar ES6 ma bhi karwa deta hy